### ISSUE TITLE
{ "name": "Exception" } error when trying to update existing form

### ISSUE THREAD

**Issue by emir1nemir** [kubohiroya/sheet2form#23]
I would need help. I tried to update a form that I created earlier with sheet2form, but when I use the "Export form" or the "Export form..." command, it gives me the error: form export failed. { "name": "Exception" }.

Please, help.

Thank you,
Emir

**Comment by kubohiroya** [comment]
Hi, Emir.

Please provide a minimal example of a Google Spreadsheet with errors.

**Comment by emir1nemir** [comment]
Thank you for your reply.
Please, check out the spreadsheet:
https://docs.google.com/spreadsheets/d/1iohegTO8P4AU8dGKO3Zy8reLHwcR-w7wQ30foConS90/edit?usp=sharing
I would really appreciate your help.
When I delete the URLs in the spreadsheet, it creates a new form without a problem. But if I leave the URLs and want to update the existing form, then the error occurs.

Thank you!

**Comment by kubohiroya** [comment]
The reported trouble can be reproduced in my environment.
Please update your script with new one:
https://raw.githubusercontent.com/kubohiroya/sheet2form/master/dist/sheet2form.gs

**Comment by emir1nemir** [comment]
Thank you so much! Its working now!
